#!/usr/bin/zsh

# Text editors
alias vim="nvim"  # uses /usr/local/bin or /usr/bin
alias ovim="/usr/bin/vim"
alias vimo="/usr/bin/vim"
alias vimdiff="nvim -d"

# sudo
alias visudo='sudo visudo'
alias supac='sudo pacman'
alias sue='sudoedit'
alias please='sudo $(fc -ln -1)'  # rerun previous command as sudo

# ls
alias ls='ls -hF --color=auto --group-directories-first'
alias ll='ls -lA'
alias lr='ls -R'
alias la='ls -A'
alias lla='ll -a'

alias grep='grep --color=auto'
alias df='df -h'
alias du='du -ch'
alias ping='ping -c 5'

# Safety
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# dotfiles git management
alias dot='/usr/bin/git --git-dir=$DOTREPO --work-tree=$HOME'

alias cls='echo -ne "\033c"'  # clear terminal screen
