#!/usr/bin/zsh

shell_profile=${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile
[ -f $shell_profile ] && source $shell_profile

typeset shells=( shell sh bash zsh )

for file in $XDG_CONFIG_HOME/*/env; do
  typeset to_source=true
  for shell in $shells; do
    if [[ $file == $XDG_CONFIG_HOME/$shell/env ]]; then
      to_source=false
      break
    fi
  done
  if $to_source; then
    print $file sourced
    source $file
  else
    print $file not sourced
  fi
done

export rc_source=()

export HISTFILE="${XDG_STATE_HOME}/zsh/history"
