#!/usr/bin/zsh

# basic options
setopt nobeep
setopt noclobber

# cd
setopt autocd
setopt cdablevars
cdpath=( . ~ ~/.local ~/projects / )

# directory stack
setopt autopushd
setopt pushdignoredups
setopt pushdsilent
DIRSTACKSIZE=30
# alias d='dirs -v'
# for index ({1..9}) alias "$index"="cd +${index}"; unset index

# history
setopt appendhistory
setopt incappendhistory
setopt extendedhistory
setopt histignoredups
setopt histfindnodups
setopt histreduceblanks
export HISTFILE=$XDG_STATE_HOME/zsh/history

precmd_functions=()

# Ctrl+d exits on filled command line
exit_zsh() { exit }
zle -N exit_zsh
bindkey '^D' exit_zsh

autoload -Uz $ZDOTDIR/funcs/*(.:t)

# vim

# cursor mode switching
function zle-keymap-select () {
  case $KEYMAP in
    vicmd) echo -ne '\e[1 q';;       # block
    viins|main) echo -ne '\e[5 q';;  # beam
  esac
}
zle -N zle-keymap-select
zle-line-init() {
  echo -ne '\e[5 q'
}
zle -N zle-line-init
echo -ne '\e[5 q'
preexec() { echo -ne '\e[5 q' ;}

[ -f $ZDOTDIR/prompts ] && source $ZDOTDIR/prompts

zmodload zsh/complist
autoload -Uz compinit; compinit
[ -f $ZDOTDIR/completion ] && source $ZDOTDIR/completion

[ -f $ZDOTDIR/aliases ] && source $ZDOTDIR/aliases

bindkey -v
export KEYTIMEOUT=75
[ -f $ZDOTDIR/binds ] && source $ZDOTDIR/binds

[ -f $ZPLUGDIR/zsh-bd/bd.zsh ] && source $ZPLUGDIR/zsh-bd/bd.zsh
# if [[ -f $ZPLUGDIR/zsh-syntax-highlighting/zsh-syntax-highlighting]]; then
#   source $ZPLUGDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# fi
