#!/usr/bin/env zsh


# This file is supposed to have all my zsh keybindings, but in all honestly, it's really just getting vi-mode to act how I want
# Getting vi-mode to act how I want mostly means "closer to vim"


bindkey -v
export KEYTIMEOUT=75

# cursor mode switching: underscore for normal mode and line for insert
# (at time of comment I use a block cursor for alacritty vi mode)
function zle-keymap-select () {
  case $KEYMAP in
    vicmd) echo -ne '\e[4 q';;       # underscore
    viins|main) echo -ne '\e[6 q';;  # beam
  esac
}
zle -N zle-keymap-select

# always start new prompt in insert mode
zle-line-init() {
  echo -ne '\e[5 q'
}
zle -N zle-line-init
echo -ne '\e[5 q'
preexec() { echo -ne '\e[5 q' ;}

bindkey -rpM viins '\e'
bindkey -M viins 'jj' vi-cmd-mode

bindkey -M viins "^[[A" up-line-or-history
bindkey -M viins "^[[B" down-line-or-history
bindkey -M viins "^[[C" vi-forward-char
bindkey -M viins "^[[D" vi-backward-char

# bindkey -M viins '<TAB>' complete-


bindkey -M vicmd '^p' history-search-backward
bindkey -M vicmd '^n' history-search-forward

# bindkey -M vicmd '^M-p'
# bindkey -M vicmd '^M-n'


bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
