#!/usr/bin/env zsh

shell_profile=${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile
[ -f "$shell_profile" ] && source "$shell_profile"

typeset -U path
path=( ~/.local/bin ~/.local/sbin ~/.local/share/cargo/bin $path )

typeset -U fpath
fpath=( "$ZDOTDIR"/funcs/**/ $fpath )

typeset -U manpath
manpath=( "$XDG_DATA_HOME"/man $manpath )

typeset -U infopath
infopath=( "$XDG_DATA_HOME"/info $infopath )

[ -f "$DOTDIR"/profile.local ] && source "$DOTDIR"/profile.local
