#!/usr/bin/env zsh


# Most my personal zsh setup is here or sourced from here :3
# within my system, this file is sourced when starting any new terminal (it's just symbolic linked to `.zshrc`) so it should be easier to adjust on the fly
# sources a bunch of other files to keep things somewhat organized, for the most part in this file options are just set


# basic options
setopt nobeep

# cd
setopt auto_cd
setopt chase_dots
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent
DIRSTACKSIZE=30

# alias d='dirs -v'
# for index ({1..9}) alias "$index"="cd +${index}"; unset index

# completion
setopt auto_list
setopt auto_menu
setopt auto_param_keys
setopt auto_param_slash
setopt auto_remove_slash
setopt glob_complete
setopt no_list_ambiguous

# globbing
setopt extendedglob
setopt mark_dirs

# history
setopt append_history
setopt extended_history
setopt hist_fcntl_lock
setopt hist_find_no_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_lex_words
setopt hist_reduce_blanks
setopt inc_append_history_time

export HISTFILE=$XDG_STATE_HOME/zsh/history
export HISTSIZE=10000
export SAVEHIST=10000

# io
setopt no_clobber
setopt clobber_empty
setopt hash_cmds
setopt hash_dirs
setopt path_dirs

setopt check_jobs

export LISTMAX=0

precmd_functions=()

# Ctrl+d exits on filled command line
exit_zsh() { exit }
zle -N exit_zsh
bindkey '^D' exit_zsh

autoload -Uz $ZDOTDIR/funcs/*  # (.:t)

# my prompt
[ -f $ZDOTDIR/prompts ] && source $ZDOTDIR/prompts

# completion functions
zmodload zsh/complist
fpath=( $ZPLUGDIR/zsh-completions/src $fpath )
autoload -Uz compinit; compinit -d $XDG_CACHE_HOME/zsh/compdump
[ -f $ZDOTDIR/completion ] && source $ZDOTDIR/completion

# my aliases
[ -f $ZDOTDIR/aliases ] && source $ZDOTDIR/aliases

# my keybinds
[ -f $ZDOTDIR/binds ] && source $ZDOTDIR/binds

# plugins
ZPLUGDIR=$XDG_DATA_HOME/zsh/plugins
[ -f $ZPLUGDIR/zsh-bd/bd.zsh ] && source $ZPLUGDIR/zsh-bd/bd.zsh
# if [[ -f $ZPLUGDIR/zsh-syntax-highlighting/zsh-syntax-highlighting]]; then
#   source $ZPLUGDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# fi

# for zoxide completions to work
eval "$(zoxide init zsh)"

typeset ignore=( pnpm )
# source other local stuff I might have
for file in "$XDG_CONFIG_HOME"/*/rc; do
  typeset to_source=true
  for shell in "${shells[@]}"; do
    if [[ $file == $XDG_CONFIG_HOME/$shell/rc ]]; then
      to_source=false
      break
    fi
  done
  if [[ !to_source ]]; then break; fi
  for program in "${ignore[@]}"; do
    if [[ $file == $XDG_CONFIG_HOME/$program/rc ]]; then
      to_source=false
      break
    fi
  done
  if "$to_source"; then
    source "$file"
  else
  fi
done

[ -f $ZDOTDIR/rc.local ] && source $ZDOTDIR/rc.local
