#!/usr/bin/env zsh

# basic options
setopt nobeep

# cd
setopt auto_cd
setopt chase_dots
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent
DIRSTACKSIZE=30

# alias d='dirs -v'
# for index ({1..9}) alias "$index"="cd +${index}"; unset index

# completion
setopt auto_list
setopt auto_menu
setopt auto_param_keys
setopt auto_param_slash
setopt auto_remove_slash
setopt glob_complete
setopt no_list_ambiguous

# globbing
setopt extendedglob
setopt mark_dirs

# history
setopt append_history
setopt extended_history
setopt hist_fcntl_lock
setopt hist_find_no_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_lex_words
setopt hist_reduce_blanks
setopt inc_append_history_time

# io
setopt no_clobber
setopt clobber_empty
setopt hash_cmds
setopt hash_dirs
setopt path_dirs

setopt check_jobs

export LISTMAX=0

precmd_functions=()

# Ctrl+d exits on filled command line
exit_zsh() { exit }
zle -N exit_zsh
bindkey '^D' exit_zsh

autoload -Uz $ZDOTDIR/funcs/*  # (.:t)

# vim

# cursor mode switching
function zle-keymap-select () {
  case $KEYMAP in
    vicmd) echo -ne '\e[4 q';;       # underline
    viins|main) echo -ne '\e[6 q';;  # beam
  esac
}
zle -N zle-keymap-select
zle-line-init() {
  echo -ne '\e[5 q'
}
zle -N zle-line-init
echo -ne '\e[5 q'
preexec() { echo -ne '\e[5 q' ;}

[ -f $ZDOTDIR/prompts ] && source $ZDOTDIR/prompts

zmodload zsh/complist
fpath=( $ZPLUGDIR/zsh-completions/src $fpath )
autoload -Uz compinit; compinit -d $XDG_CACHE_HOME/zsh/compdump
[ -f $ZDOTDIR/completion ] && source $ZDOTDIR/completion

[ -f $ZDOTDIR/aliases ] && source $ZDOTDIR/aliases

bindkey -v
export KEYTIMEOUT=75
[ -f $ZDOTDIR/binds ] && source $ZDOTDIR/binds

ZPLUGDIR=$XDG_DATA_HOME/zsh/plugins
[ -f $ZPLUGDIR/zsh-bd/bd.zsh ] && source $ZPLUGDIR/zsh-bd/bd.zsh
# if [[ -f $ZPLUGDIR/zsh-syntax-highlighting/zsh-syntax-highlighting]]; then
#   source $ZPLUGDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# fi

eval "$(zoxide init zsh)"

[ -f $ZDOTDIR/rc.local ] && source $ZDOTDIR/rc.local
