#!/usr/bin/sh

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.local/cache
export XDG_STATE_HOME=$HOME/.local/state
export XDG_DATA_HOME=$HOME/.local/share

export TERMINAL="alacritty"
export EDITOR="nvim"
export VISUAL="nvim"
export RUNNER="rofi -show run"
export BROWSER="firefox"

export HOSTNAME=$HOST

PATH="$HOME/.local/bin:$PATH"
