#!/hint/zsh

# function to easily source user environment or shell config files
# src [program] [file ...]
# if there is a directory matching *program* in $XDG_CONFIG_HOME, all listed files in
# the directory will be sourced
# if there is not a directory matching, *program* defaults to $SHELL
# if no file is listed, the program attempts to source rc, and if it fails, then env

typeset search_for
search_for=(rc env)

typeset dir=${SHELL:t}
if [[ $# -gt 0 && -d "${XDG_CONFIG_HOME}/$1" ]]; then
  dir=$1
  shift
fi

print "searching in directory ${dir}..."

if [[ $# -eq 0 ]]; then
  for filename in $search_for; do
    typeset file="${XDG_CONFIG_HOME}/${dir}/${filename}"
    print "Sourcing ${file}..."
    if [[ -f $file ]]; then
      source $file
      return
    fi
  done
  print "Unable to find files $search_for in $dir"
else
  for filename in $*; do
    typeset file="${XDG_CONFIG_HOME}/${dir}/${filename}"
    print "Sourcing ${file}..."
    if [[ -f $file ]]; then
      source $file
    else
      print "$file does not exist"
    fi
  done
fi
