" follow XDG guidelines
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_CONFIG_HOME/vim,$XDG_DATA_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir, 'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir, 'p')

set viminfofile=$XDG_STATE_HOME/vim/viminfo


" key bindings
inoremap jj <Esc>
nnoremap s <C-W>
vnoremap . <Esc>

cmap w!! w !sudo tee > /dev/null %

" indentation
set autoindent
filetype plugin indent on
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=0 "auto-indents match tabstop

" misc
syntax on
set number
set nowrap
set incsearch
set noerrorbells
set belloff=all
"set colorcolumn=100
"highlight ColorColumn ctermbg=13

" C++
autocmd BufEnter *.tpp :setlocal filetype=cpp

" makefiles
au BufRead,BufNewFile makefile set noexpandtab

let check="VIMRC LOADED"
