#!/usr/bin/zsh

/usr/bin/python3 -m venv env
source env/bin/activate

env/bin/python3 -m pip install --upgrade pip

if [[ -f requirements.txt ]]; then
  env/bin/python3 -m pip install -r requirements.txt
fi

ln -s env/bin/activate act

if [[ ! -f .gitignore ]]; then
  cp $XDG_TEMPLATES_DIR/python/gitignore .gitignore
fi
