[general]
live_config_reload = true
import = ["~/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_night.toml"]


[window]
decorations = "None"
title = "Alacritty"
dynamic_title = true

[window.class]
instance = "alacritty"
general = "alacritty"

[scrolling]
history = 50000


[font]
size = 11.0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiLight"

[font.italic]
style = "SemiLight Italic"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"


[cursor]
unfocused_hollow = true

# Typing cursor
[cursor.style]
shape = "Beam"

# Motion cursor
[cursor.vi_mode_style]
shape = "Block"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"


[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
key = "NumpadEnter"
mods = "None"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "NumpadEnter"
mods = "Shift"
action = "ReceiveChar"
